# Generated by Django 2.0.10 on 2019-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('0', 'FREE'), ('1', 'BUDDY'), ('2', 'VIP')], default='0', max_length=255, verbose_name='Type of Subscription'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription valid until'),
        ),
    ]
