# Generated by Django 2.0.10 on 2019-02-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190211_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(choices=[('0', 'MONTHLY'), ('1', 'MONTHLY DISCOUNT'), ('2', 'YEARLY')], default='0', max_length=255, verbose_name='Subscription Deal')),
                ('payment_complete', models.BooleanField(default=False, verbose_name='Payment Completed')),
                ('payment_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Completion Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
