# Generated by Django 2.0.10 on 2019-02-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190221_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Confirm to subscribe to the Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_facebook_account',
            field=models.BooleanField(default=False, verbose_name='Confirm that you have a valid facebook account'),
        ),
    ]
