# Generated by Django 2.0.10 on 2019-02-21 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190221_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeline_of_datapoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=55, verbose_name='Invite Code for Signup'),
        ),
    ]
