# Generated by Django 2.0.10 on 2019-02-10 11:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Date Time')),
                ('fbid_data', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('ownership_check', models.BooleanField(default=False, verbose_name='Ownership of Data confirmed by User')),
                ('integrated', models.BooleanField(default=False, verbose_name='Datapoint is integrated in Friends')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datapoint',
                'verbose_name_plural': 'Datapoints',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=255, verbose_name='Facebook ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Friend Name')),
                ('notes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notes')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Friends/', verbose_name='Friend Avatar')),
                ('timestamps', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=[], size=None)),
                ('ranks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('social_signals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friends',
                'ordering': ['-fbid'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('owner', 'fbid')},
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together={('owner', 'datetime')},
        ),
    ]
