# Generated by Django 2.0.10 on 2019-02-04 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='fbid_data',
            field=models.TextField(default='', validators=[django.core.validators.int_list_validator], verbose_name='FB ID Rank Data'),
            preserve_default=False,
        ),
    ]
