# Generated by Django 2.0.10 on 2019-02-05 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_datapoint_fbid_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='description',
        ),
        migrations.AddField(
            model_name='friend',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='fbid_data',
            field=models.TextField(validators=[django.core.validators.int_list_validator], verbose_name='FB ID Ranked Data'),
        ),
    ]
