# Generated by Django 2.0.10 on 2019-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20190210_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='last_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Rank'),
        ),
    ]
