# Generated by Django 2.0.10 on 2019-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20190205_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='ownership_check',
            field=models.BooleanField(default=False, verbose_name='The uploaded data is mine.'),
        ),
    ]
