# Generated by Django 2.0.10 on 2019-02-05 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_datapoint_ownership_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['datetime'], 'verbose_name': 'Datapoint', 'verbose_name_plural': 'Datapoints'},
        ),
        migrations.AddField(
            model_name='friend',
            name='ranks',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.int_list_validator], verbose_name='FB Rank Timeseries'),
        ),
        migrations.AddField(
            model_name='friend',
            name='timestamps',
            field=models.TextField(blank=True, null=True, verbose_name='Sequential Timestamps of Data'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='ownership_check',
            field=models.BooleanField(default=False, verbose_name='Ownership of Data confirmed by User'),
        ),
    ]
