# Generated by Django 2.0.10 on 2019-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_friend_last_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='source_code',
            field=models.TextField(blank=True, help_text='Source Code of the main facebook page', null=True, verbose_name='FB Page Source Code'),
        ),
    ]
