# Generated by Django 2.0.10 on 2019-02-05 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_auto_20190205_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='ranks',
            field=models.TextField(default='[]', validators=[django.core.validators.int_list_validator], verbose_name='FB Rank Timeseries'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='timestamps',
            field=models.TextField(default='[]', verbose_name='Sequential Timestamps of Data'),
        ),
    ]
