# Generated by Django 2.0.10 on 2019-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_datapoint_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='fbid_data',
            field=models.TextField(blank=True, help_text='String of comma-separated list of facebook ids: ["123","456",...]', null=True, verbose_name='FB ID List'),
        ),
    ]
