# Generated by Django 2.0.10 on 2019-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20190205_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Friend Name'),
        ),
    ]
