# Generated by Django 2.0.10 on 2019-02-05 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0008_auto_20190205_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-fbid'], 'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
        migrations.AddField(
            model_name='friend',
            name='last_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Facebook ID'),
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together={('owner', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('owner', 'fbid')},
        ),
    ]
