# Generated by Django 2.0.10 on 2019-02-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20190211_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='total_social_signals',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Social Signals'),
        ),
        migrations.AddField(
            model_name='friend',
            name='total_volatility',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Volatility'),
        ),
    ]
