# Generated by Django 2.0.10 on 2019-02-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_auto_20190214_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='total_movement',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Rank Movement'),
        ),
    ]
