# Generated by Django 2.0.10 on 2019-02-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0012_friend_comparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='comparison',
            field=models.BooleanField(default=False, verbose_name='Add to comparison chart'),
        ),
    ]
