# Generated by Django 2.0.10 on 2019-02-22 07:39

from django.db import migrations, models
import facebook.models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0013_auto_20190222_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='color',
            field=models.CharField(default=facebook.models.generate_random_color, max_length=7, verbose_name='Color of Chart'),
        ),
    ]
